//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinSerRankingCierre.ServicioMercadeo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/MarketingPersonal.PedidosWebAD.Services.R" +
        "equests.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WinSerRankingCierre.ServicioMercadeo.RealityCrucero))]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PwdSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SesionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioSistemaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PwdSistema {
            get {
                return this.PwdSistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.PwdSistemaField, value) != true)) {
                    this.PwdSistemaField = value;
                    this.RaisePropertyChanged("PwdSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SesionId {
            get {
                return this.SesionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SesionIdField, value) != true)) {
                    this.SesionIdField = value;
                    this.RaisePropertyChanged("SesionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioSistema {
            get {
                return this.UsuarioSistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioSistemaField, value) != true)) {
                    this.UsuarioSistemaField = value;
                    this.RaisePropertyChanged("UsuarioSistema");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealityCrucero", Namespace="http://schemas.datacontract.org/2004/07/MarketingPersonal.PedidosWebAD.Services.R" +
        "equests.Negocio")]
    [System.SerializableAttribute()]
    public partial class RealityCrucero : WinSerRankingCierre.ServicioMercadeo.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinSerRankingCierre.ServicioMercadeo.RealityCrucero1 RequestField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinSerRankingCierre.ServicioMercadeo.RealityCrucero1 Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealityCrucero", Namespace="http://schemas.datacontract.org/2004/07/MarketingPersonal.PedidosWebAD.Services.E" +
        "ntidades")]
    [System.SerializableAttribute()]
    public partial class RealityCrucero1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampanaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailgroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorDevolucionCampana10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorDevolucionCampana8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorDevolucionCampana9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorPedidoCampana10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorPedidoCampana8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorPedidoCampana9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campana {
            get {
                return this.CampanaField;
            }
            set {
                if ((object.ReferenceEquals(this.CampanaField, value) != true)) {
                    this.CampanaField = value;
                    this.RaisePropertyChanged("Campana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mailgroup {
            get {
                return this.MailgroupField;
            }
            set {
                if ((object.ReferenceEquals(this.MailgroupField, value) != true)) {
                    this.MailgroupField = value;
                    this.RaisePropertyChanged("Mailgroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorDevolucionCampana10 {
            get {
                return this.ValorDevolucionCampana10Field;
            }
            set {
                if ((this.ValorDevolucionCampana10Field.Equals(value) != true)) {
                    this.ValorDevolucionCampana10Field = value;
                    this.RaisePropertyChanged("ValorDevolucionCampana10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorDevolucionCampana8 {
            get {
                return this.ValorDevolucionCampana8Field;
            }
            set {
                if ((this.ValorDevolucionCampana8Field.Equals(value) != true)) {
                    this.ValorDevolucionCampana8Field = value;
                    this.RaisePropertyChanged("ValorDevolucionCampana8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorDevolucionCampana9 {
            get {
                return this.ValorDevolucionCampana9Field;
            }
            set {
                if ((this.ValorDevolucionCampana9Field.Equals(value) != true)) {
                    this.ValorDevolucionCampana9Field = value;
                    this.RaisePropertyChanged("ValorDevolucionCampana9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorPedidoCampana10 {
            get {
                return this.ValorPedidoCampana10Field;
            }
            set {
                if ((this.ValorPedidoCampana10Field.Equals(value) != true)) {
                    this.ValorPedidoCampana10Field = value;
                    this.RaisePropertyChanged("ValorPedidoCampana10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorPedidoCampana8 {
            get {
                return this.ValorPedidoCampana8Field;
            }
            set {
                if ((this.ValorPedidoCampana8Field.Equals(value) != true)) {
                    this.ValorPedidoCampana8Field = value;
                    this.RaisePropertyChanged("ValorPedidoCampana8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorPedidoCampana9 {
            get {
                return this.ValorPedidoCampana9Field;
            }
            set {
                if ((this.ValorPedidoCampana9Field.Equals(value) != true)) {
                    this.ValorPedidoCampana9Field = value;
                    this.RaisePropertyChanged("ValorPedidoCampana9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zona {
            get {
                return this.ZonaField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonaField, value) != true)) {
                    this.ZonaField = value;
                    this.RaisePropertyChanged("Zona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/MarketingPersonal.PedidosWebAD.Services.R" +
        "esponses.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WinSerRankingCierre.ServicioMercadeo.RealityCrucero2))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito {
            get {
                return this.ExitoField;
            }
            set {
                if ((this.ExitoField.Equals(value) != true)) {
                    this.ExitoField = value;
                    this.RaisePropertyChanged("Exito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealityCrucero", Namespace="http://schemas.datacontract.org/2004/07/MarketingPersonal.PedidosWebAD.Services.R" +
        "esponses.Negocio")]
    [System.SerializableAttribute()]
    public partial class RealityCrucero2 : WinSerRankingCierre.ServicioMercadeo.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinSerRankingCierre.ServicioMercadeo.RealityCrucero1 ResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinSerRankingCierre.ServicioMercadeo.RealityCrucero1 Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioMercadeo.IMercadeo")]
    public interface IMercadeo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMercadeo/ConsultarRealityCrucero", ReplyAction="http://tempuri.org/IMercadeo/ConsultarRealityCruceroResponse")]
        WinSerRankingCierre.ServicioMercadeo.RealityCrucero2 ConsultarRealityCrucero(WinSerRankingCierre.ServicioMercadeo.RealityCrucero request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMercadeo/ConsultarRealityCrucero", ReplyAction="http://tempuri.org/IMercadeo/ConsultarRealityCruceroResponse")]
        System.Threading.Tasks.Task<WinSerRankingCierre.ServicioMercadeo.RealityCrucero2> ConsultarRealityCruceroAsync(WinSerRankingCierre.ServicioMercadeo.RealityCrucero request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMercadeoChannel : WinSerRankingCierre.ServicioMercadeo.IMercadeo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MercadeoClient : System.ServiceModel.ClientBase<WinSerRankingCierre.ServicioMercadeo.IMercadeo>, WinSerRankingCierre.ServicioMercadeo.IMercadeo {
        
        public MercadeoClient() {
        }
        
        public MercadeoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MercadeoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MercadeoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MercadeoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinSerRankingCierre.ServicioMercadeo.RealityCrucero2 ConsultarRealityCrucero(WinSerRankingCierre.ServicioMercadeo.RealityCrucero request) {
            return base.Channel.ConsultarRealityCrucero(request);
        }
        
        public System.Threading.Tasks.Task<WinSerRankingCierre.ServicioMercadeo.RealityCrucero2> ConsultarRealityCruceroAsync(WinSerRankingCierre.ServicioMercadeo.RealityCrucero request) {
            return base.Channel.ConsultarRealityCruceroAsync(request);
        }
    }
}
