//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.ServicioMercadeo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/MarketingPersonal.PedidosWebAD.Services.R" +
        "equests.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AccesoDatos.ServicioMercadeo.PuntajeAsesora))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AccesoDatos.ServicioMercadeo.RealityCrucero))]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PwdAppField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SesionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioAppField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PwdApp {
            get {
                return this.PwdAppField;
            }
            set {
                if ((object.ReferenceEquals(this.PwdAppField, value) != true)) {
                    this.PwdAppField = value;
                    this.RaisePropertyChanged("PwdApp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SesionId {
            get {
                return this.SesionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SesionIdField, value) != true)) {
                    this.SesionIdField = value;
                    this.RaisePropertyChanged("SesionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioApp {
            get {
                return this.UsuarioAppField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioAppField, value) != true)) {
                    this.UsuarioAppField = value;
                    this.RaisePropertyChanged("UsuarioApp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PuntajeAsesora", Namespace="http://schemas.datacontract.org/2004/07/MarketingPersonal.PedidosWebAD.Services.R" +
        "equests.Negocio")]
    [System.SerializableAttribute()]
    public partial class PuntajeAsesora : AccesoDatos.ServicioMercadeo.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AccesoDatos.ServicioMercadeo.PuntajeAsesora1 RequestField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccesoDatos.ServicioMercadeo.PuntajeAsesora1 Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealityCrucero", Namespace="http://schemas.datacontract.org/2004/07/MarketingPersonal.PedidosWebAD.Services.R" +
        "equests.Negocio")]
    [System.SerializableAttribute()]
    public partial class RealityCrucero : AccesoDatos.ServicioMercadeo.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AccesoDatos.ServicioMercadeo.RealityCruceroConsulta RequestField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccesoDatos.ServicioMercadeo.RealityCruceroConsulta Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealityCruceroConsulta", Namespace="http://schemas.datacontract.org/2004/07/MarketingPersonal.PedidosWebAD.Services.E" +
        "ntidades")]
    [System.SerializableAttribute()]
    public partial class RealityCruceroConsulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampanaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campana {
            get {
                return this.CampanaField;
            }
            set {
                if ((object.ReferenceEquals(this.CampanaField, value) != true)) {
                    this.CampanaField = value;
                    this.RaisePropertyChanged("Campana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PuntajeAsesora", Namespace="http://schemas.datacontract.org/2004/07/MarketingPersonal.PedidosWebAD.Services.E" +
        "ntidades")]
    [System.SerializableAttribute()]
    public partial class PuntajeAsesora1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampanaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DevolucionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PuntosInsentivosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campana {
            get {
                return this.CampanaField;
            }
            set {
                if ((object.ReferenceEquals(this.CampanaField, value) != true)) {
                    this.CampanaField = value;
                    this.RaisePropertyChanged("Campana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Devoluciones {
            get {
                return this.DevolucionesField;
            }
            set {
                if ((this.DevolucionesField.Equals(value) != true)) {
                    this.DevolucionesField = value;
                    this.RaisePropertyChanged("Devoluciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoField, value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PuntosInsentivos {
            get {
                return this.PuntosInsentivosField;
            }
            set {
                if ((this.PuntosInsentivosField.Equals(value) != true)) {
                    this.PuntosInsentivosField = value;
                    this.RaisePropertyChanged("PuntosInsentivos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zona {
            get {
                return this.ZonaField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonaField, value) != true)) {
                    this.ZonaField = value;
                    this.RaisePropertyChanged("Zona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/MarketingPersonal.PedidosWebAD.Services.R" +
        "esponses.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AccesoDatos.ServicioMercadeo.PuntajeAsesora2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AccesoDatos.ServicioMercadeo.RealityCrucero1))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito {
            get {
                return this.ExitoField;
            }
            set {
                if ((this.ExitoField.Equals(value) != true)) {
                    this.ExitoField = value;
                    this.RaisePropertyChanged("Exito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PuntajeAsesora", Namespace="http://schemas.datacontract.org/2004/07/MarketingPersonal.PedidosWebAD.Services.R" +
        "esponses.Negocio")]
    [System.SerializableAttribute()]
    public partial class PuntajeAsesora2 : AccesoDatos.ServicioMercadeo.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AccesoDatos.ServicioMercadeo.PuntajeAsesora1[] ListaPuntajesAsesoraField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccesoDatos.ServicioMercadeo.PuntajeAsesora1[] ListaPuntajesAsesora {
            get {
                return this.ListaPuntajesAsesoraField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaPuntajesAsesoraField, value) != true)) {
                    this.ListaPuntajesAsesoraField = value;
                    this.RaisePropertyChanged("ListaPuntajesAsesora");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealityCrucero", Namespace="http://schemas.datacontract.org/2004/07/MarketingPersonal.PedidosWebAD.Services.R" +
        "esponses.Negocio")]
    [System.SerializableAttribute()]
    public partial class RealityCrucero1 : AccesoDatos.ServicioMercadeo.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AccesoDatos.ServicioMercadeo.RealityCrucero2[] ResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccesoDatos.ServicioMercadeo.RealityCrucero2[] Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealityCrucero", Namespace="http://schemas.datacontract.org/2004/07/MarketingPersonal.PedidosWebAD.Services.E" +
        "ntidades")]
    [System.SerializableAttribute()]
    public partial class RealityCrucero2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampanaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailgroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorDevolucionCampana10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorDevolucionCampana8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorDevolucionCampana9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorPedidoCampana10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorPedidoCampana8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorPedidoCampana9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campana {
            get {
                return this.CampanaField;
            }
            set {
                if ((object.ReferenceEquals(this.CampanaField, value) != true)) {
                    this.CampanaField = value;
                    this.RaisePropertyChanged("Campana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mailgroup {
            get {
                return this.MailgroupField;
            }
            set {
                if ((object.ReferenceEquals(this.MailgroupField, value) != true)) {
                    this.MailgroupField = value;
                    this.RaisePropertyChanged("Mailgroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorDevolucionCampana10 {
            get {
                return this.ValorDevolucionCampana10Field;
            }
            set {
                if ((this.ValorDevolucionCampana10Field.Equals(value) != true)) {
                    this.ValorDevolucionCampana10Field = value;
                    this.RaisePropertyChanged("ValorDevolucionCampana10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorDevolucionCampana8 {
            get {
                return this.ValorDevolucionCampana8Field;
            }
            set {
                if ((this.ValorDevolucionCampana8Field.Equals(value) != true)) {
                    this.ValorDevolucionCampana8Field = value;
                    this.RaisePropertyChanged("ValorDevolucionCampana8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorDevolucionCampana9 {
            get {
                return this.ValorDevolucionCampana9Field;
            }
            set {
                if ((this.ValorDevolucionCampana9Field.Equals(value) != true)) {
                    this.ValorDevolucionCampana9Field = value;
                    this.RaisePropertyChanged("ValorDevolucionCampana9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorPedidoCampana10 {
            get {
                return this.ValorPedidoCampana10Field;
            }
            set {
                if ((this.ValorPedidoCampana10Field.Equals(value) != true)) {
                    this.ValorPedidoCampana10Field = value;
                    this.RaisePropertyChanged("ValorPedidoCampana10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorPedidoCampana8 {
            get {
                return this.ValorPedidoCampana8Field;
            }
            set {
                if ((this.ValorPedidoCampana8Field.Equals(value) != true)) {
                    this.ValorPedidoCampana8Field = value;
                    this.RaisePropertyChanged("ValorPedidoCampana8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorPedidoCampana9 {
            get {
                return this.ValorPedidoCampana9Field;
            }
            set {
                if ((this.ValorPedidoCampana9Field.Equals(value) != true)) {
                    this.ValorPedidoCampana9Field = value;
                    this.RaisePropertyChanged("ValorPedidoCampana9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zona {
            get {
                return this.ZonaField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonaField, value) != true)) {
                    this.ZonaField = value;
                    this.RaisePropertyChanged("Zona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioMercadeo.IMercadeo")]
    public interface IMercadeo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMercadeo/ConsultarRealityCrucero", ReplyAction="http://tempuri.org/IMercadeo/ConsultarRealityCruceroResponse")]
        AccesoDatos.ServicioMercadeo.RealityCrucero1 ConsultarRealityCrucero(AccesoDatos.ServicioMercadeo.RealityCrucero request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMercadeo/ConsultarRealityCrucero", ReplyAction="http://tempuri.org/IMercadeo/ConsultarRealityCruceroResponse")]
        System.Threading.Tasks.Task<AccesoDatos.ServicioMercadeo.RealityCrucero1> ConsultarRealityCruceroAsync(AccesoDatos.ServicioMercadeo.RealityCrucero request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMercadeo/ConsultarPuntajeAsesora", ReplyAction="http://tempuri.org/IMercadeo/ConsultarPuntajeAsesoraResponse")]
        AccesoDatos.ServicioMercadeo.PuntajeAsesora2 ConsultarPuntajeAsesora(AccesoDatos.ServicioMercadeo.PuntajeAsesora request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMercadeo/ConsultarPuntajeAsesora", ReplyAction="http://tempuri.org/IMercadeo/ConsultarPuntajeAsesoraResponse")]
        System.Threading.Tasks.Task<AccesoDatos.ServicioMercadeo.PuntajeAsesora2> ConsultarPuntajeAsesoraAsync(AccesoDatos.ServicioMercadeo.PuntajeAsesora request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMercadeoChannel : AccesoDatos.ServicioMercadeo.IMercadeo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MercadeoClient : System.ServiceModel.ClientBase<AccesoDatos.ServicioMercadeo.IMercadeo>, AccesoDatos.ServicioMercadeo.IMercadeo {
        
        public MercadeoClient() {
        }
        
        public MercadeoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MercadeoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MercadeoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MercadeoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AccesoDatos.ServicioMercadeo.RealityCrucero1 ConsultarRealityCrucero(AccesoDatos.ServicioMercadeo.RealityCrucero request) {
            return base.Channel.ConsultarRealityCrucero(request);
        }
        
        public System.Threading.Tasks.Task<AccesoDatos.ServicioMercadeo.RealityCrucero1> ConsultarRealityCruceroAsync(AccesoDatos.ServicioMercadeo.RealityCrucero request) {
            return base.Channel.ConsultarRealityCruceroAsync(request);
        }
        
        public AccesoDatos.ServicioMercadeo.PuntajeAsesora2 ConsultarPuntajeAsesora(AccesoDatos.ServicioMercadeo.PuntajeAsesora request) {
            return base.Channel.ConsultarPuntajeAsesora(request);
        }
        
        public System.Threading.Tasks.Task<AccesoDatos.ServicioMercadeo.PuntajeAsesora2> ConsultarPuntajeAsesoraAsync(AccesoDatos.ServicioMercadeo.PuntajeAsesora request) {
            return base.Channel.ConsultarPuntajeAsesoraAsync(request);
        }
    }
}
